[package]
name = "ele_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
image = "0.25.9"
chrono = "0.4"
anyhow = "1.0"
log = "0.4"
simplelog = "0.12"
electron-bot = { git = "https://github.com/TOTHTOT/ElectronBotLib.git" }
BotEyes = { git = "https://github.com/TOTHTOT/BotEyes" }
sherpa-rs = { version = "0.6", features = ["tts", "download-binaries"] }
cpal = "0.17.1"
rodio = "0.19"
toml = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
candle-core = "0.8"
candle-transformers = "0.8"
tokenizers = "0.21"

[profile.release]
opt-level = 3
lto = "fat"          # 深度链接优化
codegen-units = 1    # 减少代码生成单元，增加优化机会
panic = "abort"      # 减小二进制体积，稍微提升速度