[package]
name = "ele_bot"
version = "0.1.0"
edition = "2021"

[features]
default = []
fps-counter = []

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
image = "0.25.9"
chrono = "0.4"
anyhow = "1.0"
log = "0.4"
simplelog = "0.12"
electron-bot = { git = "https://github.com/TOTHTOT/ElectronBotLib.git", version = "0.1.0" }
BotEyes = { git = "https://github.com/TOTHTOT/BotEyes" , version = "0.1.2"}
toml = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# ASR+TTS 推理 (sherpa-onnx)
sherpa-onnx = "1"

# 音频管理, 获取系统音频输入输出
cpal = "0.17.1"

# 离线llm推理, 跑 gguf 模型
candle-core = "0.9"
candle-transformers = "0.9"
tokenizers = "0.22.2"

# Online LLM (使用 async-openai 调用)
async-openai = { version = "0.34.0", features = ["_api", "chat-completion", "chat-completion-types"] }

# Web server for preview
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }
base64 = "0.22"
async-stream = "0.3"
bytes = "1"

# 模型管理, 自动下载需要的模型
hf-hub = "0.5.0"

# Camera capture
[target.'cfg(windows)'.dependencies]
nokhwa = { version = "0.10.10", features = ["input-native"] }
[target.'cfg(unix)'.dependencies]
nokhwa = { version = "0.10.10", features = ["input-v4l"] }
[target.'cfg(target_os = "macos")'.dependencies]
nokhwa = { version = "0.10.10", features = ["input-avfoundation"] }

# RKNN only for aarch64 linux (RK3566/RK3588)
[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))'.dependencies]
rknn-rs = "0.2.4"
librga = { git = "https://github.com/TOTHTOT/librga-rs.git" }
# 离线人脸识别, pc 平台使用, rk3566调用rknn
[target.'cfg(not(all(target_os = "linux", target_arch = "aarch64")))'.dependencies]
ort = { version = "2.0.0-rc.12", default-features = false, features = ["std", "ndarray", "load-dynamic", "api-24", "tls-native"] }

[profile.release]
opt-level = 3
#lto = "fat"          # 深度链接优化
#codegen-units = 1    # 减少代码生成单元，增加优化机会
panic = "abort"      # 减小二进制体积，稍微提升速度
# 提高了编译速度
lto = "thin"       # 改用 thin LTO
codegen-units = 16 # 增加并行度
