FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge
RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y libasound2-dev:arm64 libssl-dev:arm64 pkg-config
COPY assets/lib/librknnrt.so /usr/lib/aarch64-linux-gnu/